/* eslint-disable */
// Generated by Wrangler

declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "EdgePersonaAgent";
  }
}

interface Env {
  EdgePersonaAgent: DurableObjectNamespace<
    import("./src/agent").EdgePersonaAgent
  >;

  AI: Ai;            // Workers AI
  VEC: VectorizeIndex;    // Vectorize memory
  AI_GATEWAY_NAME: string;
}
